CREATE TABLE IF NOT EXISTS `proj-sales-recommender-dev.sales_recommender_dev.construct_connect_feed`(
  ProjectID INT64,
  DataSourceID STRING,
  Title STRING,
  Stage STRING,
  URL STRING,
  UpdateDate STRING,
  IsProspective BOOL,
  UpdateText STRING,
  Valuation_Value STRING,
  Valuation_Currency STRING,
  Valuation_ValueType STRING,
  Parameters_Parameter_Ownership STRING,
  Parameters_Parameter_WorkType STRING,
  Parameters_Parameter_CommenceDate STRING,
  Parameters_Parameter_CompletionDate STRING,
  Parameters_Parameter_FloorsAboveGround FLOAT64,
  Parameters_Parameter_Structures FLOAT64,
  Parameters_Parameter_Units FLOAT64,
  Parameters_Parameter_BidDate STRING,
  Parameters_Parameter_BidTime STRING,
  Parameters_Parameter_IsSingleTrade BOOL,
  DocumentAvailability_Plans BOOL,
  DocumentAvailability_Specs BOOL,
  DocumentAvailability_Addenda BOOL,
  ParentCategories_PrimaryCategoryName STRING,
  ParentCategories_ParentCategory ARRAY<STRUCT<Name STRING, SubCategories STRUCT<SubCategory ARRAY<STRING>>>>,
  Addresses_Address ARRAY<STRUCT<ProjectAddressType STRING, AddressLine1 STRING, AddressLine2 STRING, City STRING, CountryRegion STRING, County STRING, Latitude NUMERIC, Longitude NUMERIC, StateProvince STRING, ZipPostalCode STRING>>,
  Contracts_Contract ARRAY<STRUCT<BidDate STRING, BidTime STRING, BidType STRING, BidsTo STRING, Bonding STRING, Classification STRING, Invitation STRING, PlansFrom STRING>>,
  ProjectEvents_ProjectEvent ARRAY<STRUCT<Event STRING, EventDate STRING, EventDetails STRING, EventTime STRING>>,
  Companies ARRAY<STRUCT<Company ARRAY<STRUCT<BiddingRole STRING, CompanyID INT64, DataSourceID STRING, LastUpdate STRING, Name STRING, Role STRING, URL STRING, Addresses STRUCT<Address ARRAY<STRUCT<AddressType STRING, AddressLine1 STRING, AddressLine2 STRING, City STRING, CountryRegion STRING, County STRING, StateProvince STRING, ZipPostalCode STRING>>>, BidderRoles STRUCT<Bidder ARRAY<STRUCT<BidCreateDate STRING, BidRank INT64, BidValue STRING, BidderClassification STRING>>>, ClassificationTypes STRUCT<ClassificationType ARRAY<STRUCT<Rank INT64, Type STRING>>>, Contacts STRUCT<Contact ARRAY<STRUCT<ContactID STRING, Name STRING, Email STRING, LinkedInURL STRING, PhoneNumber STRING>>>, Email STRING, ParticipantRoles STRUCT<ParticipantRole STRUCT<ContactId STRING, ContactName STRING, RoleClassification STRING, RoleStatus STRING>>, Phones STRUCT<Phone ARRAY<STRUCT<PhoneNumnber STRING, PhoneType STRING>>>, Website STRING>>>>,
  Users ARRAY<STRUCT<User ARRAY<STRUCT<ProjectFlaggedForExport BOOL, UserFullName STRING, UserId STRING, UserName STRING, Queries STRUCT<Query ARRAY<STRUCT<DocCenterUrl STRING, QueryId STRING, QueryName STRING>>>>>>>,
  UpdateSummarizations_UpdateSummary ARRAY<STRUCT<Summary STRING, UpdateSummaryDate STRING>>,
  PlanSpecs ARRAY<STRUCT<PlanSpec STRUCT<Deposit STRING, `From` STRING, URL STRING, PlanRoom ARRAY<STRUCT<Bin STRING, PlanRoom STRING, URL STRING>>>>>,
  Details_Detail_Scope ARRAY<STRING>,
  Details_Detail_Notes ARRAY<STRING>,
  Details_Detail ARRAY<STRUCT<DetailType STRING, _ STRING>>,
  RSMeansMaterialDivisions_Division_Concrete ARRAY<STRUCT<Code INT64, InstallationCostValue NUMERIC, MaterialCostValue NUMERIC, TotalCostValue NUMERIC, _ STRING>>,
  RSMeansMaterialDivisions_Division_Metals ARRAY<STRUCT<Code INT64, InstallationCostValue NUMERIC, MaterialCostValue NUMERIC, TotalCostValue NUMERIC, _ STRING>>,
  RSMeansMaterialDivisions_Division_WoodPlasticsandComposites ARRAY<STRUCT<Code INT64, InstallationCostValue NUMERIC, MaterialCostValue NUMERIC, TotalCostValue NUMERIC, _ STRING>>,
  RSMeansMaterialDivisions_Division_ThermalandMoistureProtection ARRAY<STRUCT<Code INT64, InstallationCostValue NUMERIC, MaterialCostValue NUMERIC, TotalCostValue NUMERIC, _ STRING>>,
  RSMeansMaterialDivisions_Division_Openings ARRAY<STRUCT<Code INT64, InstallationCostValue NUMERIC, MaterialCostValue NUMERIC, TotalCostValue NUMERIC, _ STRING>>,
  RSMeansMaterialDivisions_Division_Finishes ARRAY<STRUCT<Code INT64, InstallationCostValue NUMERIC, MaterialCostValue NUMERIC, TotalCostValue NUMERIC, _ STRING>>,
  RSMeansMaterialDivisions_Division_Furnishings ARRAY<STRUCT<Code INT64, InstallationCostValue NUMERIC, MaterialCostValue NUMERIC, TotalCostValue NUMERIC, _ STRING>>,
  RSMeansMaterialDivisions_Division_ConveyingEquipment ARRAY<STRUCT<Code INT64, InstallationCostValue NUMERIC, MaterialCostValue NUMERIC, TotalCostValue NUMERIC, _ STRING>>,
  RSMeansMaterialDivisions_Division_FireSuppression ARRAY<STRUCT<Code INT64, InstallationCostValue NUMERIC, MaterialCostValue NUMERIC, TotalCostValue NUMERIC, _ STRING>>,
  RSMeansMaterialDivisions_Division_Plumbing ARRAY<STRUCT<Code INT64, InstallationCostValue NUMERIC, MaterialCostValue NUMERIC, TotalCostValue NUMERIC, _ STRING>>,
  RSMeansMaterialDivisions_Division_HeatingVentilatingandAirConditioningHVAC ARRAY<STRUCT<Code INT64, InstallationCostValue NUMERIC, MaterialCostValue NUMERIC, TotalCostValue NUMERIC, _ STRING>>,
  RSMeansMaterialDivisions_Division_Electrical ARRAY<STRUCT<Code INT64, InstallationCostValue NUMERIC, MaterialCostValue NUMERIC, TotalCostValue NUMERIC, _ STRING>>,
  RSMeansMaterialDivisions_Division_Communications ARRAY<STRUCT<Code INT64, InstallationCostValue NUMERIC, MaterialCostValue NUMERIC, TotalCostValue NUMERIC, _ STRING>>,
  RSMeansMaterialDivisions_Division_ElectronicSafetyandSecurity ARRAY<STRUCT<Code INT64, InstallationCostValue NUMERIC, MaterialCostValue NUMERIC, TotalCostValue NUMERIC, _ STRING>>,
  RSMeansMaterialDivisions_Division_Earthwork ARRAY<STRUCT<Code INT64, InstallationCostValue NUMERIC, MaterialCostValue NUMERIC, TotalCostValue NUMERIC, _ STRING>>,
  RSMeansMaterialDivisions_Division_Utilities ARRAY<STRUCT<Code INT64, InstallationCostValue NUMERIC, MaterialCostValue NUMERIC, TotalCostValue NUMERIC, _ STRING>>,
  Notes INT64,
  ListDate STRING,
  Connections ARRAY<INT64>,
  Details_Detail_Details ARRAY<STRING>,
  Materials_Material ARRAY<STRUCT<Code INT64, _ STRING>>,
  ProjectParentID FLOAT64,
  Parameters_Parameter_FloorArea FLOAT64,
  Parameters_Parameter_FloorAreaUnitofMeasure STRING,
  RSMeansMaterialDivisions_Division_Specialties ARRAY<STRUCT<Code INT64, InstallationCostValue NUMERIC, MaterialCostValue NUMERIC, TotalCostValue NUMERIC, _ STRING>>,
  RSMeansMaterialDivisions_Division_Masonry ARRAY<STRUCT<Code INT64, InstallationCostValue NUMERIC, MaterialCostValue NUMERIC, TotalCostValue NUMERIC, _ STRING>>,
  RSMeansMaterialDivisions_Division_Equipment ARRAY<STRUCT<Code INT64, InstallationCostValue NUMERIC, MaterialCostValue NUMERIC, TotalCostValue NUMERIC, _ STRING>>,
  Parameters_Parameter_MandatoryPreBidConferenceDate STRING,
  RSMeansMaterialDivisions_Division_GeneralRequirements ARRAY<STRUCT<Code INT64, InstallationCostValue NUMERIC, MaterialCostValue NUMERIC, TotalCostValue NUMERIC, _ STRING>>,
  RSMeansMaterialDivisions_Division_SpecialConstruction ARRAY<STRUCT<Code INT64, InstallationCostValue NUMERIC, MaterialCostValue NUMERIC, TotalCostValue NUMERIC, _ STRING>>,
  Parameters_Parameter_SingleTradeClassification STRING,
  Parameters_Parameter_LEEDCertificationIntent STRING,
  Parameters_Parameter_FloorsBelowGround FLOAT64,
  Parameters_Parameter_ParkingSpaces FLOAT64,
  Parameters_Parameter_SiteArea FLOAT64,
  Parameters_Parameter_SiteAreaUnitofMeasure STRING,
  Parameters_Parameter_GreenBuildingCertification STRING,
  Notes_Note ARRAY<STRUCT<CreateDate STRING, ModifyDate STRING, NoteId STRING, NoteText STRING, UserId STRING>>,
  sourceFile STRING OPTIONS(description="XML Source File name "),
  time_created DATETIME DEFAULT CURRENT_DATETIME() OPTIONS(description="Record creation time in BigQuery."),
  sourceFileCreationTime STRING OPTIONS(description="Time when XML file was uploaded to GCS"),
  Details_Detail_ContractConditions ARRAY<STRING>,
  Details FLOAT64,
  Details_Detail_Subbids ARRAY<STRING>,
  Details_Detail_QuantityUnitprices ARRAY<STRING>,
  Details_Detail_Status ARRAY<STRING>,
  PRIMARY KEY (ProjectID) NOT ENFORCED
)
PARTITION BY DATE(time_created)
CLUSTER BY ProjectID,sourceFile,sourceFileCreationTime;
