name: 'Manual Cloud Tasks'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment (dev or prod)'
        required: true
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy-tasks:
    name: 'Deploy Google Cloud Tasks'
    runs-on: ubuntu-24.04
    environment: ${{ github.event.inputs.environment }}
    defaults:
      run:
        working-directory: deploy

    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v2

      # Authenticate to Google Cloud
      - name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      # Set up Google Cloud SDK
      - name: 'Set up Google Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}


      # Run the script to create Cloud tasks
      - name: 'Run Cloud tasks Script'
        run: |
          if [ "${{ github.event.inputs.environment }}" == "dev" ]; then
            chmod +x  create_cloud_task_dev.sh
            ./create_cloud_task_dev.sh
          elif [ "${{ github.event.inputs.environment }}" == "prod" ]; then
            chmod +x create_cloud_task_prod.sh
            ./create_cloud_task_prod.sh
          fi